### ISSUE TITLE
Network must be specified for recognition from audio

### ISSUE THREAD

**Issue by yaroslavkoretskyi** [nassosoassos/sail_align#4]
Good day,
I'm try to use your program.
run like this:
sail_align -i support / data / billion.wav -t support / data / billion.txt -w support / test / local -e timit_sample_test -c config / timit_alignment.cfg

But get this error:

[FATAL](/usr/local/share/perl/5.18.2/SailTools/SailHtkWrapper.pm line 414) HVite failed:  ERROR [+3230]  HVite: Network must be specified for recognition from audio

 FATAL ERROR - Terminating program /home/maximus/sail_align/bin/HVite
[FATAL](/usr/local/share/perl/5.18.2/SailTools/SailHtkWrapper.pm line 475) HERest global adaptation failed:2
[FATAL](/usr/local/share/perl/5.18.2/SailTools/SailHtkWrapper.pm line 486) HERest regression class tree adaptation failed:2
[FATAL](/usr/local/share/perl/5.18.2/SailTools/SailHtkWrapper.pm line 414) HVite failed:  ERROR [+3230]  HVite: Network must be specified for recognition from audio

 FATAL ERROR - Terminating program /home/maximus/sail_align/bin/HVite
[FATAL](/usr/local/share/perl/5.18.2/SailTools/SailHtkWrapper.pm line 475) HERest global adaptation failed:2
[FATAL](/usr/local/share/perl/5.18.2/SailTools/SailHtkWrapper.pm line 486) HERest regression class tree adaptation failed:2
[FATAL](/usr/local/share/perl/5.18.2/SailTools/SailHtkWrapper.pm line 414) HVite failed:  ERROR [+3230]  HVite: Network must be specified for recognition from audio

 FATAL ERROR - Terminating program /home/maximus/sail_align/bin/HVite
[FATAL](/usr/local/share/perl/5.18.2/SailTools/SailHtkWrapper.pm line 475) HERest global adaptation failed:2
[FATAL](/usr/local/share/perl/5.18.2/SailTools/SailHtkWrapper.pm line 486) HERest regression class tree adaptation failed:2
[FATAL](/usr/local/share/perl/5.18.2/SailTools/SailHtkWrapper.pm line 414) HVite failed:  ERROR [+8220]  LatticeFromLabels: Word !!unk not defined in dictionary

 FATAL ERROR - Terminating program /home/maximus/sail_align/bin/HVite
[FATAL](/usr/local/share/perl/5.18.2/SailTools/SailHtkWrapper.pm line 414) HVite failed:  ERROR [+8220]  LatticeFromLabels: Word !!unk not defined in dictionary

 FATAL ERROR - Terminating program /home/maximus/sail_align/bin/HVite

Please tell me why this error can be and how it can fix
Thanks for the reply

**Comment by nassosoassos** [comment]
Hi,

could you please also send me the alignment.log file to see what may be
wrong? Is the audio file you are testing the program with sampled at 16kHz?

best,
nassos

**Comment by nassosoassos** [comment]
The problem is the sampling rate. Please try downsampling your audio to
16kHz (You can do it using sox.)
The models included with sail_align have only been trained at 16kHz and
won't work correctly with 48kHz audio.

best,
nassos

**Comment by saikrishnar** [comment]
Sir,
I've tried using your code and I've verified that the wave file is of 16Khz. I ran it on the timit test sentence to be sure. But still the same error persists. Also, its  single channel wavefile.
![sail_align_error](https://cloud.githubusercontent.com/assets/6652883/6509804/cc58f27a-c387-11e4-8f37-6e15555b4aaa.png)

This is in the alignment.log:

DEBUG - /home/tejas/Documents/sail_align/bin/ngram-count -wbdiscount -unk -map-unk !!UNK -limit-vocab first/wordlists/words.list.2.5-3.15 -text first/text/first_segment2.5-3.15.txt -order 3 -lm first/lm/f$
DEBUG - In get_files abs_list: n_files=0 file=first/first_segment.seg
DEBUG - Results set initialized OK!
DEBUG - /home/tejas/Documents/sail_align/bin/HDecode -T 1 -C first/asr.cfg -t 150.0 -o S -p -4.0 -s 15.0 -J first/adaptation/xforms mllr2 -h '*/%%*.mfc' -m -J first/adaptation/classes -H /home/tejas/Docum$
DEBUG - /home/tejas/Documents/sail_align/bin/HVite -T 1 -l first/asr -m  -o S -a -C first/hvite_alignment.cfg -t 250.0 150.0 1000.0 -J first/adaptation/xforms mllr2 -h '*/%%*.mfc' -k -J first/adaptation/c$
FATAL - HVite failed:  ERROR [+3230]  HVite: Network must be specified for recognition from audio

 FATAL ERROR - Terminating program /home/tejas/Documents/sail_align/bin/HVite

DEBUG - first/asr
DEBUG - first/asr
DEBUG - /home/tejas/Documents/sail_align/bin/sclite -i wsj -h first/text_align/hyp_first_segment.2.5-3.15 -r first/text_align/ref_first_segment.9-10. -O first/text_align -o pralign
WARN - Something wrong with speech recognition or text alignment, true words: 2 found words: 0
INFO - Number of aligned words in the segment/total number of words: 0/0
INFO - Alignment iteration: 2 Alignment percentage: 0.818181818181818



Please suggest.

**Comment by nassosoassos** [comment]
It appears that the program has worked fine. You can safely ignore these
errors. They just indicate that there were a few small subsegments that
were not properly aligned, but as it seems you already have a relatively
high alignment percentage: 81% I guess the program has gone up to iteration
5, right?
The final results should then be in the first_segment.lab file or in
first_segment.forced.phn and first_segment.forced.wrd.

best,
nassos

**Comment by tuming1990** [comment]
I met the same problem...

I use MATLAB to resample each audio file from 44.1K to 16K. Also I make sure that each audio file is 16 bit PCM. But only some of the files could pass the test. There must be problem of my original audio file. Then, I use a simple acoustic model to recognize all audio files using HTK and there is no error. I don't know why sail_align doesn't work. Is there any particular requirement of the input format? Thanks.

**Comment by saikrishnar** [comment]
Can you please give a link to one of the files with error?

Thanks and Regards,

Sai Krishna
Researcher in Speech Sciences,
Speech and Vision Lab,
International Institute of Information Technology- Hyderabad

researchweb.iiit.ac.in/~saikrishna.r

%%%%%%%%%%%%%

Try n learn\* every bit of\* your core ....and a _bit of every_ other
Research field.

Jg jut _OQ_ ibse, zpv ibwfo'u usjfe fopvhi
 #&%// - Reverse ceaser crypted with '1'

%%%%%%%%%%%%%

**Comment by tuming1990** [comment]
Thanks. One audio file is here:
https://drive.google.com/open?id=0B0KTrVVi-n-1TU9mVmk3dWxrejA&authuser=0

**Comment by beenotes** [comment]
Could you please also send me the alignment.log file in your working directory for a file that does not pass the test? 

thanks,
nassos

**Comment by nassosoassos** [comment]
Could you please also send me the alignment.log file in the working directory for an audio file that does not pass the test?

thanks,
nassos

**Comment by tuming1990** [comment]
Thanks. I put it here...

DEBUG - File appender has been added.
DEBUG - audio:../alsf9_rhythm1.wav text: ../alsf9_rhythm1.txt
DEBUG - Initialized experiment speech_alignment, working dir: ../temp/
DEBUG - Successfully initialized a SailSignal instance
DEBUG - Initialized transcription
DEBUG - Properly initialized alignment
DEBUG - Signal: ../alsf9_rhythm1.wav Number of transcribed words: 9
DEBUG - File's duration is: 5.905 sec
DEBUG - ../temp/features/asr/htk/../alsf9_rhythm1.mfc
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/HCopy -T 1 -C ../temp/feature_extraction.cfg ../alsf9_rhythm1.wav ../temp/features/asr/htk/../alsf9_rhythm1.mfc
DEBUG - Feature extraction finished OK
DEBUG - Starting feature file segmentation
DEBUG - Starting feature file segmentation: n_segments = 1 ../temp/alsf9_rhythm1.seg
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/ch_track ../temp/features/asr/htk/../alsf9_rhythm1.mfc -otype htk -cut_file ../temp/alsf9_rhythm1.cut
DEBUG - Number of existing files after segmentation: 1
DEBUG - Feature file segmentation finished OK
DEBUG - Number of Unique words in the transcription: 9
DEBUG - Number of words in the reference dictionary: 132835
DEBUG - Number of unknown words in the transcription: 0
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/ngram-count -wbdiscount -unk -map-unk !!UNK -limit-vocab ../temp/wordlists/words.list -text ../temp/text/alsf9_rhythm1.txt -order 3 -lm ../temp/lm/alsf9_rhythm1.lm 
DEBUG - In get_files abs_list: n_files=1 file=../temp/alsf9_rhythm1.seg
DEBUG - Results set initialized OK!
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/HDecode -T 1 -C ../temp/asr.cfg -t 150.0 -o S -p -4.0 -s 15.0 -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/hmmdefs -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/macros -l ../temp/asr -S ../temp/alsf9_rhythm1.seg -w ../temp/lm/alsf9_rhythm1.lm ../temp/dictionary /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/tiedlist
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/HVite -T 1 -l ../temp/asr -m  -o S -C ../temp/hvite_alignment.cfg -b '<s>' -a -t 250.0 150.0 1000.0 -L ../temp/asr -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/hmmdefs -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/macros -X rec -y rec -S ../temp/alsf9_rhythm1.seg ../temp/dictionary /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/tiedlist
DEBUG - Number of words in the hypothesis file: 7
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/sclite -i wsj -h ../temp/text_align/hyp_alsf9_rhythm1 -r ../temp/text_align/ref_alsf9_rhythm1 -O ../temp/text_align -o pralign
INFO - Alignment iteration: 1 Alignment percentage: 0
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/HHEd -T 1 -B -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/macros -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/hmmdefs -M ../temp/adaptation/classes ../temp/adaptation/regtree.hed /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/tiedlist
DEBUG - Starting feature file segmentation: n_segments = 0 ../temp/alsf9_rhythm1.seg
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/ch_track ../temp/features/asr/htk/../alsf9_rhythm1.mfc -otype htk -cut_file ../temp/alsf9_rhythm1.cut
DEBUG - Number of existing files after segmentation: 0
DEBUG - Number of segments to be checked for adaptation: 0
DEBUG - In get_files abs_list: n_files=0 file=../temp/alsf9_rhythm1.seg
DEBUG - In get_files abs_list: n_files=0 file=../temp/adaptation/adaptation_files.scp
DEBUG - Number of aligned segments used for adaptation: 0
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/HVite -T 1 -l '*' -i ../temp/adaptation/adaptation.mlf -m  -o SWT -C ../temp/hvite_alignment.cfg -b '<s>' -a -t 250.0 150.0 1000.0 -L ../temp/adaptation -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/hmmdefs -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/macros -X lab -y lab -S ../temp/adaptation/adaptation_files.scp ../temp/dictionary /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/tiedlist
FATAL - HVite failed:  ERROR [+3230]  HVite: Network must be specified for recognition from audio

 FATAL ERROR - Terminating program /home/ming/Documents/Work/Software/sail_align-master/bin/HVite

DEBUG - Number of aligned segments used for adaptation: 0
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/HERest -T 1 -C ../temp/adaptationconfig.global -S ../temp/adaptation/adaptation_files.scp -I ../temp/adaptation/adaptation.mlf -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/macros -u a -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/hmmdefs -K ../temp/adaptation/xforms mllr1  -J ../temp/adaptation/classes -h '_/%%_.mfc' /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/tiedlist
FATAL - HERest global adaptation failed:2
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/HERest -T 1 -C ../temp/adaptationconfig.rc -a -S ../temp/adaptation/adaptation_files.scp -I ../temp/adaptation/adaptation.mlf -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/macros -u a -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/hmmdefs -K ../temp/adaptation/xforms mllr2 -J ../temp/adaptation/xforms mllr1 -J ../temp/adaptation/classes -h '_/%%_.mfc' /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/tiedlist
FATAL - HERest regression class tree adaptation failed:2
DEBUG - current_unaligned_index=0 ind = 0 number_of_segs = 1
DEBUG - unaligned_index=0 start: 0 end: -1
DEBUG - Skipped segment because of unexpectedly short duration.Probably problematic transcription at this point.

INFO - Alignment iteration: 2 Alignment percentage: 0
DEBUG - Starting feature file segmentation: n_segments = 0 ../temp/alsf9_rhythm1.seg
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/ch_track ../temp/features/asr/htk/../alsf9_rhythm1.mfc -otype htk -cut_file ../temp/alsf9_rhythm1.cut
DEBUG - Number of existing files after segmentation: 0
DEBUG - Number of segments to be checked for adaptation: 0
DEBUG - In get_files abs_list: n_files=0 file=../temp/alsf9_rhythm1.seg
DEBUG - In get_files abs_list: n_files=0 file=../temp/adaptation/adaptation_files.scp
DEBUG - Number of aligned segments used for adaptation: 0
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/HVite -T 1 -l '*' -i ../temp/adaptation/adaptation.mlf -m  -o SWT -C ../temp/hvite_alignment.cfg -b '<s>' -a -t 250.0 150.0 1000.0 -L ../temp/adaptation -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/hmmdefs -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/macros -X lab -y lab -S ../temp/adaptation/adaptation_files.scp ../temp/dictionary /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/tiedlist
FATAL - HVite failed:  ERROR [+3230]  HVite: Network must be specified for recognition from audio

 FATAL ERROR - Terminating program /home/ming/Documents/Work/Software/sail_align-master/bin/HVite

DEBUG - Number of aligned segments used for adaptation: 0
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/HERest -T 1 -C ../temp/adaptationconfig.global -S ../temp/adaptation/adaptation_files.scp -I ../temp/adaptation/adaptation.mlf -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/macros -u a -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/hmmdefs -K ../temp/adaptation/xforms mllr1  -J ../temp/adaptation/classes -h '_/%%_.mfc' /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/tiedlist
FATAL - HERest global adaptation failed:2
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/HERest -T 1 -C ../temp/adaptationconfig.rc -a -S ../temp/adaptation/adaptation_files.scp -I ../temp/adaptation/adaptation.mlf -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/macros -u a -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/hmmdefs -K ../temp/adaptation/xforms mllr2 -J ../temp/adaptation/xforms mllr1 -J ../temp/adaptation/classes -h '_/%%_.mfc' /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/tiedlist
FATAL - HERest regression class tree adaptation failed:2
DEBUG - current_unaligned_index=0 ind = 0 number_of_segs = 1
DEBUG - unaligned_index=0 start: 0 end: -1
DEBUG - Skipped segment because of unexpectedly short duration.Probably problematic transcription at this point.

INFO - Alignment iteration: 3 Alignment percentage: 0
DEBUG - Starting feature file segmentation: n_segments = 0 ../temp/alsf9_rhythm1.seg
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/ch_track ../temp/features/asr/htk/../alsf9_rhythm1.mfc -otype htk -cut_file ../temp/alsf9_rhythm1.cut
DEBUG - Number of existing files after segmentation: 0
DEBUG - Number of segments to be checked for adaptation: 0
DEBUG - In get_files abs_list: n_files=0 file=../temp/alsf9_rhythm1.seg
DEBUG - In get_files abs_list: n_files=0 file=../temp/adaptation/adaptation_files.scp
DEBUG - Number of aligned segments used for adaptation: 0
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/HVite -T 1 -l '*' -i ../temp/adaptation/adaptation.mlf -m  -o SWT -C ../temp/hvite_alignment.cfg -b '<s>' -a -t 250.0 150.0 1000.0 -L ../temp/adaptation -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/hmmdefs -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/macros -X lab -y lab -S ../temp/adaptation/adaptation_files.scp ../temp/dictionary /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/tiedlist
FATAL - HVite failed:  ERROR [+3230]  HVite: Network must be specified for recognition from audio

 FATAL ERROR - Terminating program /home/ming/Documents/Work/Software/sail_align-master/bin/HVite

DEBUG - Number of aligned segments used for adaptation: 0
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/HERest -T 1 -C ../temp/adaptationconfig.global -S ../temp/adaptation/adaptation_files.scp -I ../temp/adaptation/adaptation.mlf -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/macros -u a -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/hmmdefs -K ../temp/adaptation/xforms mllr1  -J ../temp/adaptation/classes -h '_/%%_.mfc' /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/tiedlist
FATAL - HERest global adaptation failed:2
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/HERest -T 1 -C ../temp/adaptationconfig.rc -a -S ../temp/adaptation/adaptation_files.scp -I ../temp/adaptation/adaptation.mlf -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/macros -u a -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/hmmdefs -K ../temp/adaptation/xforms mllr2 -J ../temp/adaptation/xforms mllr1 -J ../temp/adaptation/classes -h '_/%%_.mfc' /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/tiedlist
FATAL - HERest regression class tree adaptation failed:2
DEBUG - current_unaligned_index=0 ind = 0 number_of_segs = 1
DEBUG - unaligned_index=0 start: 0 end: -1
DEBUG - Skipped segment because of unexpectedly short duration.Probably problematic transcription at this point.

INFO - Alignment iteration: 4 Alignment percentage: 0
DEBUG - current_unaligned_index=0 ind = 0 number_of_segs = 1
DEBUG - unaligned_index=0 start: 0 end: -1
DEBUG - Skipped segment because of unexpectedly short duration.Probably problematic transcription at this point.

INFO - Alignment iteration: 5 Alignment percentage: 0
DEBUG - Forced word alignment started.
WARN - Problematic beginning of a segment. Skipping.
INFO - 1 utterances have been found in split_into_utterances.
DEBUG - Starting feature file segmentation: n_segments = 1 ../temp/alsf9_rhythm1.seg
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/ch_track ../temp/features/asr/htk/../alsf9_rhythm1.mfc -otype htk -cut_file ../temp/alsf9_rhythm1.cut
DEBUG - Number of existing files after segmentation: 1
DEBUG - In get_files abs_list: n_files=1 file=../temp/alsf9_rhythm1.seg
DEBUG - Number of aligned segments used for adaptation: 1
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/HVite -T 1 -l '_' -i ../temp/word/word_align.mlf -o SM -C ../temp/hvite_word_alignment.cfg -b '<s>' -a -t 250.0 150.0 1000.0 -L ../temp/word -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/hmmdefs -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/macros -X lab -y lab -S ../temp/word/files.list ../temp/dictionary /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/tiedlist
DEBUG - Forced phone alignment started.
WARN - Problematic beginning of a segment. Skipping.
INFO - 1 utterances have been found in split_into_utterances.
DEBUG - Starting feature file segmentation: n_segments = 1 ../temp/alsf9_rhythm1.seg
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/ch_track ../temp/features/asr/htk/../alsf9_rhythm1.mfc -otype htk -cut_file ../temp/alsf9_rhythm1.cut
DEBUG - Number of existing files after segmentation: 1
DEBUG - In get_files abs_list: n_files=1 file=../temp/alsf9_rhythm1.seg
DEBUG - Number of aligned segments used for adaptation: 1
DEBUG - /home/ming/Documents/Work/Software/sail_align-master/bin/HVite -T 1 -l '_' -i ../temp/phone/phone_align.mlf -m  -o SW -C ../temp/hvite_alignment.cfg -b '<s>' -a -t 250.0 150.0 1000.0 -L ../temp/phone -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/hmmdefs -H /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/macros -X lab -y lab -S ../temp/phone/files.list ../temp/dictionary /home/ming/Documents/Work/Software/sail_align-master/models/ac_models/english/htk/wsj_all_10000_32/tiedlist
DEBUG - ah

**Comment by nassosoassos** [comment]
As a general comment, to take better advantage of SailAlign I would
recommend using longer audio files, preferably with the same acoustic
background, or the same speaker. Please check the details of the algorithm
as presented here: pdf
http://cvsp.cs.ntua.gr/~nassos/pubs/KatsamanisEtAl_SailAlign_VLSRP2011.pdf.
In a short audio file like the one you sent, the recognizer may indeed find
a sequence of words but may not be able to align them with the
transcription and find appropriate anchors.

I think you should try the following:
1) In the sail_align configuration file you can set the value of the
variable min_n_aligned_words to something smaller, e.g., 3. This is the
minimum number of consecutive aligned words sailalign requires to consider
the corresponding part as reliably aligned and proceed. (please check the
algorithm for details). In the case of a challenging audio file, changing
this to something smaller, e.g., 3, is recommended.
2) As a second step you should also try concatenating all audio files by
the same speaker into a single file. This would allow sailalign to better
adapt to the speaker and the acoustic conditions and provide even better
results.

Please let me know how these work.

best,
nassos

**Comment by tuming1990** [comment]
Thanks. I will try this and let you know if there are good results.
