### ISSUE TITLE
Problems with Greek align

### ISSUE THREAD

**Issue by morkor** [nassosoassos/sail_align#6]
Hi Nassos and many thanks for this awsome tool!

I have struggled installing sail_align quite a bit, but eventually manage to get it running. It aligned without noted problems both the English and Spanish test data. However this was not the occasion for the Greek test data. At first I got some fatal errors after HERest peaked and crushed at 4GB of RAM, producing two times these errors:
[FATAL](/usr/local/lib/perl/5.18.2/SailTools/SailHtkWrapper.pm line 475) HERest global adaptation failed:2
[FATAL](/usr/local/lib/perl/5.18.2/SailTools/SailHtkWrapper.pm line 486) HERest regression class tree adaptation failed:2

Solution to this was to correct the encoding in the greeksyn_05.txt file, which for a reason was showing gibberish. After this I got a different error:
Illegal division by zero at /usr/local/lib/perl/5.18.2/SailTools/AlignSpeech.pm line 395.

I listened to the wav files and trimmed the end of the greek wav file to get rid of the trailing voices after the end of the text. Not surprisingly this did not solve anything and the same error persisted.

Please note that after installation I was getting this error related to SailTools.pm:
Can't locate SailTools.pm in @INC (you may need to install the SailTools module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /home/foo/perl5/bin/sail_align line 39.

I worked around that by copying SailTools from the sail_align-master/lib folder to the /usr/local/lib/perl/5.18.2/SailTools.

Would you have any recommendations of how to deal with the error occurring during alignment of the greek wav file?

Thank you!
Michalis

**Comment by nassosoassos** [comment]
Hi Michali,

the problem is indeed due to the RAM requirements adaptation may have in some cases. This is something I want to fix for some time now but haven't found the time yet. It appears when there is a big chunk of audio that has been properly aligned and then is used for adaptation as is, i.e., without pre segmentation into smaller pieces. This causes HERest to consume huge amounts of RAM some times. 

In any case, this is not something that should bother you. It will typically happen when alignment has worked very well even without acoustic adaptation. The example I've packed with sailalign is one such case it seems. Sailalign will recover from these adaptation errors anyway (it won't use adapted models for the following iterations if there are no such models and continue using the original acoustic models) and give proper alignments after all. Please check your working directory for the greek example and look for the files: *.lab, *.forced.wrd and *.forced.phn. They should contain the final alignment results (despite the FATAL property of the adaptation errors: I guess it has been overstated, more for debugging purposes:)) . A nice way to check the results is via wavesurfer (Create transcription pane).

Let me know if I can be of any further help.

best,
nassos

**Comment by morkor** [comment]
indeed they contain the final alignments.
Thank you for pointing this out! 

PS: Still the content in those files is gibberish when opened by gedit or geany, and only opening them in okular or in FF (and converting to UTF-8) letters display properly .

**Comment by nassosoassos** [comment]
by the way, the gibberish you are talking about is iso-8859-7 :) HTK does
not work with UTF-8 and needs this iso encoding of Greek...

Let me know if you run into any other problems.

best,
nassos

**Comment by morkor** [comment]
Thank you Nassos for your response. And in deed I got into some new fatal error territory. I tried to process another audiofile with its transcript. Running the script produced errors like:
[ERROR](/usr/local/lib/perl/5.18.2/SailTools/SailTranscription.pm line 1139) Unexpected punctuation.
and after a few more it crashed with:
[FATAL](/usr/local/lib/perl/5.18.2/SailTools/SailHtkWrapper.pm line 414) HVite failed:  ERROR [+6510]  LOpen: Unable to open label file support/test/local_greek/asr/greeksyn_05.352000-363000.rec

 FATAL ERROR - Terminating program /home/michalis/sail_align-master/bin/HVite
Illegal division by zero at /usr/local/lib/perl/5.18.2/SailTools/AlignSpeech.pm line 395.

After cleaning the text file from various strange characters, I run the script again, and still the fatal errors persisted (the Unexpected punctuation errors disappeared though). Then I also cleared the wav file from some music in the beginning, and some voices not in the transcript. Running sail_aling again produced the following error:
Illegal division by zero at /usr/local/lib/perl/5.18.2/SailTools/AlignSpeech.pm line 395.

And there was no relevant output forced.wrd or .lab files in the local_greek folder, or anywhere else inside the sail_align-master folder.

Any help is more than welcome!

Interestingly, during the various attempts to make this work, the program stopped after about 7 minutes of computing time. Even though each time errors were actually different.

Best,
Michalis

**Comment by morkor** [comment]
I also sliced the original greek text and wav file, and after running the sail_align command, the wrd still contained the original text.

**Comment by nassosoassos** [comment]
It would be helpful if you could send me the alignment.log file. By the way, have you made sure that your audio file is at 16kHz? The acoustic models have been trained on speech at 16kHz and won't work properly for audio sampled at a different frequency.

**Comment by morkor** [comment]
github does not seem to allow uploading log files. I will send it to your email address if that's ok. You were right about the frequency, it was 44.1. Changing it to 16kHz gave the same results.
Thanks again!

**Comment by nassosoassos** [comment]
So, turns out it was improper sampling frequency, improper text encoding (needed iso8859-7 instead of utf-8). Results will get better if unknown words are also added to the dictionary. Considering this issue closed:)
